<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <RootNamespace>XivVault.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\XivVault.Core\XivVault.Core.csproj" />
    <ProjectReference Include="..\..\src\XivVault.Cli\XivVault.Cli.csproj" />
    <ProjectReference Include="..\..\src\XivVault.Desktop\XivVault.Desktop.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Testing" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
