<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <RootNamespace>XIVault.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\XIVault.Core\XIVault.Core.csproj" />
    <ProjectReference Include="..\..\src\XIVault.Cli\XIVault.Cli.csproj" />
    <ProjectReference Include="..\..\src\XIVault.Desktop\XIVault.Desktop.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
