<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>XIVault.Desktop</RootNamespace>
    <AssemblyName>XIVault.Desktop</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\..\docs\brand\xivault.ico</ApplicationIcon>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XIVault.Core\XIVault.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="XIVault.Tests" />
  </ItemGroup>

</Project>
