<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>XIVault.Cli</RootNamespace>
    <AssemblyName>xivault</AssemblyName>
    <AssemblyTitle>XIV Vault command line</AssemblyTitle>
    <ApplicationIcon>..\..\docs\brand\xivault.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XIVault.Core\XIVault.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Cli" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="XIVault.Tests" />
  </ItemGroup>

</Project>
